server {
    listen 8080;
    root /usr/share/nginx/html;
    index index.html;

    location /bootc-ecosystem/ {
        try_files $uri $uri/ /bootc-ecosystem/index.html;
    }

    location = /healthz {
        return 200 "ok";
    }
}
