server {
    listen 8080;
    root /usr/share/nginx/html;
    index index.html;

    location /homebrew-stats/ {
        try_files $uri $uri/ /homebrew-stats/index.html;
    }

    location = /healthz {
        return 200 "ok";
    }
}
